### ISSUE TITLE
Async and perfomance, Chapter4 - Example is not clear enough

### ISSUE THREAD

**Issue by razouck** [getify/You-Dont-Know-JS#1171]
On section _Iterating Generators Asynchronously_, there is the following code:

```javascript
function foo(x,y) {
	ajax(
		"http://some.url.1/?x=" + x + "&y=" + y,
		function(err,data){
			if (err) {
				// throw an error into `*main()`
				it.throw( err );
			}
			else {
				// resume `*main()` with received `data`
				it.next( data );
			}
		}
	);
}

function *main() {
	try {
		var text = yield foo( 11, 31 );
		console.log( text );
	}
	catch (err) {
		console.error( err );
	}
}

var it = main();

// start it all up!
it.next();
```

It is said to be "much better" than just using callbacks. I try to understand how that code works by trying a similar code:

```javascript
function* main() {
	try {
		var text = yield foo();
		console.log(text);
	}
	catch (err) {
		console.error(err);
	}
}

function foo() {
	it.next('text');
}

var it = main();
it.next();
```

But the code fails to execute.

```
TypeError: Generator is already running
    at next (native)
    at foo (/home/darksonic/test.js:13:5)
    at main (/home/darksonic/test.js:4:20)
    at next (native)
    at Object.<anonymous> (/home/darksonic/test.js:17:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

How does the original code works, then? It is not clear enough.

**Comment by getify** [comment]
Try

```js
function foo{
  setTimeout( function() { it.next( "text" ); }, 10);
}  
```

**Comment by getify** [comment]
sorry: `function foo() {...`

**Comment by razouck** [comment]
Why does it work and not the other code? What happened?

**Comment by getify** [comment]
An `it.next(..)` call resumes a generator... but it can't be called while a generator is already running (like directly while a `yield` is still being processed). The `setTimeout(..)` (or the `ajax(..)` in the chapter) make sure `it.next(..)` is run on a later event loop tick, so it's fine to resume the paused generator at that point.

**Comment by razouck** [comment]
```javascript
function* count() {
	yield 1;
	yield 2;
	yield 3;
}

var it = count();

console.log(it.next());
console.log(it.next());
```

I called `it.next()` twice in a row. Did the generator stop running in between those calls?

**Comment by getify** [comment]
Yes

**Comment by razouck** [comment]
I understand. Thanks.
